FROM knnniggett/packpack:fedora-32-armhf
MAINTAINER Andrew Bauer <zonexpertconsulting@outlook.com>

# Our Fedora friends stopped macking arm32 images, so upgrade the previous image
RUN dnf -y update --allowerasing --releasever=33
